using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TradingServer.EnumET5
{
    public enum ET5Message
    {
        DISCONNECT_FROM_MT4,
        MT4_CAN_NOT_MAKE_COMMAND,
        CAN_NOT_CLOSE_COMMAND_FROM_MT4,
        CAN_NOT_UPDATE_COMMAND_FROM_MT4,

        NO_RESULT,
        COMMON_ERROR,
        INVALID_TRADE_PARAMETERS,
        TRADE_SERVER_IS_BUSY,
        OLD_VERSION_OF_THE_CLIENT_TERMINAL,
        NO_CONNECTION_WITH_TRADE_SERVER,
        TOO_FREQUENT_REQUESTS,
        ACCOUNT_DISABLED,
        INVALID_ACCOUNT,
        TRADE_TIMEOUT,
        INVALID_PRICE,
        INVALID_TICKET,
        INVALID_TRADE_VOLUME,
        NOT_ENOUGH_MONEY,
        OFF_QUOTES,
        INVALID_FUNCTION_PARAMETER_VALUE,
        CUSTOM_INDICATOR_ERROR,
        STRING_PARAMETER_EXPECTED,
        INTEGER_PARAMETER_EXPECTED,
        UNKNOWN_SYMBOL,
        TRADE_IS_NOT_ALLOWED_ENABLE_CHECKBOX_ALLOW_LIVE_TRADING_IN_THE_EXPERT_PROPERTIES,
        LONGS_ARE_NOT_ALLOWED_CHECK_THE_EXPERT_PROPERTIES,
        SHORTS_ARE_NOT_ALLOWED_CHECK_THE_EXPERT_PROPERTIES,
        INVALID_STOPS,
        TRADE_IS_DISABLED,
        UNKNOWN_ERROR,
        TIME_OUT,
    }
}
