//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingServer.Trading {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Trading.ITradingWCF")]
    public interface ITradingWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingWCF/ServerCommand", ReplyAction="http://tempuri.org/ITradingWCF/ServerCommandResponse")]
        string ServerCommand(string Command, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingWCF/ClientCommand", ReplyAction="http://tempuri.org/ITradingWCF/ClientCommandResponse")]
        void ClientCommand(string Command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingWCF/ServerCommandList", ReplyAction="http://tempuri.org/ITradingWCF/ServerCommandListResponse")]
        string[] ServerCommandList(string Command, string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITradingWCFChannel : TradingServer.Trading.ITradingWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TradingWCFClient : System.ServiceModel.ClientBase<TradingServer.Trading.ITradingWCF>, TradingServer.Trading.ITradingWCF {
        
        public TradingWCFClient() {
        }
        
        public TradingWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TradingWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradingWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradingWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServerCommand(string Command, string code) {
            return base.Channel.ServerCommand(Command, code);
        }
        
        public void ClientCommand(string Command) {
            base.Channel.ClientCommand(Command);
        }
        
        public string[] ServerCommandList(string Command, string code) {
            return base.Channel.ServerCommandList(Command, code);
        }
    }
}
